name: CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: Check, test & build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Type check + Biome
        run: npm run check

      # Запускаємо тести тільки якщо знайдено хоча б один файл тестів
      - name: Unit tests (Vitest)
        if: ${{ hashFiles('**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', '**/*.spec.tsx', '**/*.test.js', '**/*.test.jsx', '**/*.spec.js', '**/*.spec.jsx') != '' }}
        run: npm run test:run
        env:
          CI: true

      # Білд лише на пуш у main (PR-и не білдимо)
      - name: Build
        if: github.event_name != 'pull_request'
        run: npx vite build